name: Deploy
on:
  push:
    branches:
      - 2.0.0
jobs:
  build:
    name: Deploy plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install root node_modules
        run: yarn install

      - name: Build plugin
        working-directory: ./plugins/tatum
        run: yarn build