name: Deploy
on:
  push:
    branches:
      - 2.0.0
jobs:
  build:
    name: Deploy plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install root node_modules
        run: yarn bootstrap

      - name: Build plugin
        working-directory: ./plugins/tatum
        run: yarn build

      - name: Create directory for assets
        working-directory: ./plugins/tatum/build/tatum
        run: mkdir .wordpress-org

      - name: Copy assets
        run: cp ./plugins/tatum/wordpress.org/assets/* ./plugins/tatum/build/tatum/.wordpress-org/

      - name: Copy assets
        run: cp ./plugins/tatum/wordpress.org/assets/* ./plugins/tatum/build/tatum/.wordpress-org/

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './plugins/tatum/build/tatum'
          destination-github-username: 'tatumio'
          destination-repository-name: 'wordpress-plugin'
          user-email: lukas.kotol@tatum.io
          target-branch: deploy